//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Courses.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ClassSubject
    {
        public ClassSubject()
        {
            this.ExerciseSubjects = new HashSet<ExerciseSubject>();
        }
        [Key]
        public string IDSubject { get; set; }
        public string SubjectName { get; set; }
        public string IDClass { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual ICollection<ExerciseSubject> ExerciseSubjects { get; set; }
    }
}
