//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Courses.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Class
    {
        public Class()
        {
            this.ClassSubjects = new HashSet<ClassSubject>();
            this.Users = new HashSet<User>();
        }
        [Key]
        public string IDClass { get; set; }
        public string ClassName { get; set; }
    
        public virtual ICollection<ClassSubject> ClassSubjects { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
