//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Courses.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ExerciseSubject
    {
        [Key]
        public string IDExercise { get; set; }
        public string IDUser { get; set; }
        public string ExerciseName { get; set; }
        public string Content { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> DeadLine { get; set; }
        public string IDSubject { get; set; }
        public Nullable<double> Mark { get; set; }
    
        public virtual ClassSubject ClassSubject { get; set; }
        public virtual User User { get; set; }
    }
}
